### ISSUE TITLE
Can't install Formr

### ISSUE THREAD

**Issue by Arroyodorado** [lessthanzero/Formr#2]
I would love to try your Sketch plugin "Formr" but I cannot install it in any way. I've tried via Sketchpacks and I've tried the manual way, Sketch won't recognize the plugin. And when I doubleklick the plugin file, Sketch opens but shows no message or does not copy the plugin to the corresponding directory. I inspected the JSON file but didn't see any obvious bugs. What could be the problem?
Sketch 42 (36781), MacOS 10.11.6

**Comment by lessthanzero** [comment]
@Arroyodorado does install via Sketch Toolbox, [skpm](https://github.com/sketch-pm/skpm) or [Chest](https://github.com/Sketch-Chest/chest) work?

**Comment by lessthanzero** [comment]
@Arroyodorado hi again. I've updated plugin bundle, please, try it out. Now the installation process is correct. Seems, that the problem was with version number in `manifest.json` – in contrary to [docs](http://developer.sketchapp.com/introduction/plugin-bundles) it should be defined as a string.

**Comment by Arroyodorado** [comment]
Great, it works now. Installed via Sketchpacks and had no problems. Thank you. 8-)
